
name: arxiv_papers_analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  arxiv_papers_analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13.5
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: arxiv_papers_analyze
      run: |
        chmod +x bootstrap.sh
        ./bootstrap.sh
